import {Buffer} from 'node:buffer';
import test from 'ava';
import ResponseLike from 'responselike';
import got from '../source/index.js';

for (const headerName of ['accept-encoding', 'Accept-Encoding']) {
	test(`explicit undefined omits generated ${headerName}`, async t => {
		await got('https://example.com', {
			headers: {[headerName]: undefined},
			request(url, options) {
				t.false(Object.hasOwn(options.headers!, 'accept-encoding'));
				return new ResponseLike({
					statusCode: 200,
					headers: {},
					body: Buffer.from('ok'),
					url: url.href,
				});
			},
		});
	});
}

for (const headerValue of ['identity', '']) {
	test(`explicit accept-encoding value ${JSON.stringify(headerValue)} is preserved`, async t => {
		await got('https://example.com', {
			headers: {'accept-encoding': headerValue},
			request(url, options) {
				t.is(Reflect.get(options.headers!, 'accept-encoding'), headerValue);
				return new ResponseLike({
					statusCode: 200,
					headers: {},
					body: Buffer.from('ok'),
					url: url.href,
				});
			},
		});
	});
}

test('accept-encoding is still generated by default', async t => {
	await got('https://example.com', {
		request(url, options) {
			t.regex(String(Reflect.get(options.headers!, 'accept-encoding')), /gzip/);
			return new ResponseLike({
				statusCode: 200,
				headers: {},
				body: Buffer.from('ok'),
				url: url.href,
			});
		},
	});
});
