language: node_js
node_js:
  - '14'
  - '13'
  - '12'
  - '10'

install: npm i
script: npm run test && npm prune --production && node ./integration-test/example.js
after_success: npm i && npm run coverage
