language: node_js
node_js:
  - '14'
  - '13'
  - '12'
  - '10'
install: npm install
script: npm run test && npm prune --production && node ./integration-test/example.js
after_success: npm install && npm run coverage
