language: node_js

after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'

jobs:
  include:
    - os: linux
      dist: focal
      node_js: '15'
    - os: linux
      dist: focal
      node_js: '14'
    - os: linux
      dist: focal
      node_js: '12'
    - os: linux
      dist: focal
      node_js: '10'
    - os: linux
      dist: bionic
      node_js: '15'
    - os: linux
      dist: bionic
      node_js: '14'
    - os: linux
      dist: bionic
      node_js: '12'
    - os: linux
      dist: bionic
      node_js: '10'
    - os: windows
      node_js: '15'
    - os: windows
      node_js: '14'
    - os: windows
      node_js: '12'
    - os: windows
      node_js: '10'
    - os: osx
      osx_image: xcode12
      node_js: '15'
    - os: osx
      osx_image: xcode12
      node_js: '14'
    - os: osx
      osx_image: xcode12
      node_js: '12'
    - os: osx
      osx_image: xcode12
      node_js: '10'
