language: node_js
node_js:
  - '14'
  - '13'
  - '12'
  - '10'
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'

stages:
  - build
  - integration-tests

jobs:
  include:
    - stage: build
      name: 'Build'
      script: 'npm i && npm run build'
      after_success: [] # Override default

    - stage: integration-tests
      name: 'Integration tests'
      script: 'npm prune --production && node ./integration-test/example.js'
      after_success: [] # Override default
